### ISSUE TITLE
APK Builder does not work

### ISSUE THREAD

**Issue by v0re** [etechd/L3MON#2]
`10/7/2019, 7:15:38 AM => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/home/L3MON/server/app/factory/sign.jar" "/home/L3MON/server/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more `

**Comment by Jack-Rogers** [comment]
Hi! 

Could you please run 
`java -version` 
And send the output

Also, What OS are you running?

**Comment by Jack-Rogers** [comment]
Inactive

**Comment by zunzail** [comment]
i have this error 
Sign Command Failed - Command failed: java -jar "/home/axel/Desktop/LEMON/app/factory/sign.jar" "/home/axel/Desktop/LEMON/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more 

java -version 

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1, mixed mode, sharing)

**Comment by sudo-WearTherinG** [comment]
U might think it stuck on finalizing screen but thats not the issue,
after u try to build the apk but it's stuck u may think its not working.  go back to folder
lemon/L3MON-v1.0.0/assets/webpublic
there will be 2 apk files ( build.apk and build.s.apk ) the file u want here is named " build.apk "
send it to your android and  install it, but it will not install becouse its not signed so u have to create jar signer keystore file to sign it yourself, search on google or someting, then sign the apk yourself and wollha. u can install it and open it. login to lemon website and manage your android.

**Comment by vrushabhdhoke** [comment]
I'm getting same error of java sign error something like this.What should i do?

**Comment by AshutoshGeek** [comment]
> U might think it stuck on finalizing screen but thats not the issue,
> after u try to build the apk but it's stuck u may think its not working. go back to folder
> lemon/L3MON-v1.0.0/assets/webpublic
> there will be 2 apk files ( build.apk and build.s.apk ) the file u want here is named " build.apk "
> send it to your android and install it, but it will not install becouse its not signed so u have to create jar signer keystore file to sign it yourself, search on google or someting, then sign the apk yourself and wollha. u can install it and open it. login to lemon website and manage your android.

Can you mention specific tools to sign the apk

**Comment by vrushabhdhoke** [comment]
What actually my issue is..I installed the apk on my phone,gave all permissions manually,but in device section of l3mon website,no device is being showed,i have tried on windows 10,kali,parrot, Ubuntu

Now tell me what should i do to resolve it.
Plz suggest me something

**Comment by Mudasir121725** [comment]
hi 
i have downloading apk
![Untitled](https://user-images.githubusercontent.com/54984236/76316230-3fd07f80-6300-11ea-8df2-698b0cf78740.png)

**Comment by surajanju** [comment]
HOW TO CHECK WHETHER MY PAYLOAD IS COMMUNICATING WITH MY SERVER OR NOT BECAUSE I GOT PROBELAM CONNECTING TO MY SERVER..

**Comment by vrushabhdhoke** [comment]
Yes please resolve this,I had tried many times

**Comment by heingyi** [comment]
i download the apk but there is no phrphase in package
