### ISSUE TITLE
deploy online server

### ISSUE THREAD

**Issue by sandippshah** [etechd/L3MON#9]
how to deploy this project online on  Heroku ?

**Comment by Jack-Rogers** [comment]
The L3MON system uses file-based databases, because of this it needs persistent storage so it won't really be suitable for Heroku deploy. Additionally, L3MON uses 2 ports, one for clients and one fro administration, Heroku only allows one port! though, this could be worked around to combine socket-io to the express listener port.
Please see
1) https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted
2) https://stackoverflow.com/a/55122560/7594368

**Comment by sandippshah** [comment]
Which  hosting prefer u for this project?

**Comment by Jack-Rogers** [comment]
Grab a cheap SSD VPS from OVH with Ubuntu installed and follow the instructions found on the main page.
https://www.ovh.com/vps/

**Comment by sandippshah** [comment]
Hii bro
does  L3MON works on aws.amazon EC2 server.?

**Comment by Jack-Rogers** [comment]
It should run on anything that can run nodeJS and Java that allows you to also port forward. I can't see EC2 being an issue 👍

**Comment by sandippshah** [comment]
Thanks bro 🥰
I'm deployed this project on aws. With ec2  instance it's working good.

**Comment by sandippshah** [comment]
Can I host multiple lemon on a one
VPS?

**Comment by lordcharlx** [comment]
@sandippshah  can you tell us how ?

**Comment by Jack-Rogers** [comment]
@sandippshah Please see issue #13

**Comment by sandippshah** [comment]
Hey,

I just signed the petition "Chief Minister/Chief secretary Rajasthan State
Govt & Chief justice Rajasthan high court : Unfair court trial & in justice
in matter of Saint Shri Asharam Bapuji" and wanted to see if you could help
by adding your name.

Our goal is to reach 5,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/dc5qBb7Zgs

Thanks!
Sandip
